//USER
POST http://localhost:4000/user
Content-Type: application/json

{
    "login": "5",
    "password": "123rty"
}
###
GET http://localhost:4000/user
###
GET http://localhost:4000/user/3503ec7b-1dd4-4ef1-be8d-a251f3ace454

### 
PUT http://localhost:4000/user/b0580351-2885-4d9a-bb82-ba5291bb9ad8
Content-Type: application/json

{
    "oldPassword": "123",
    "newPassword": "236"
}
###
DELETE http://localhost:4000/user/b0580351-2885-4d9a-bb82-ba5291bb9ad8

//TRACK
###
POST http://localhost:4000/track
Content-Type: application/json

{
    "name": "123",
    "artistId": null,
    "albumId": null,
    "duration": 120
}
###
GET http://localhost:4000/track
###
GET http://localhost:4000/track/204b99c4-034c-48f8-9910-0d76bf9e9204

### 
PUT http://localhost:4000/track/204b99c4-034c-48f8-9910-0d76bf9e9205
Content-Type: application/json

{
    "name": "222",
    "artistId": null,
    "albumId": "vzick",
    "duration": 1
}
###
DELETE http://localhost:4000/track/6ad0dc9e-301e-4964-814c-6984eec39953

//ALBUM
###
POST http://localhost:4000/album
Content-Type: application/json

{
    "name": "testAlbum",
    "year": 16,
    "artistId": "linck"
}
###
GET http://localhost:4000/album
###
GET http://localhost:4000/album/b6080137-ba87-496d-9abe-6d79538ab2a8

### 
PUT http://localhost:4000/album/b6080137-ba87-496d-9abe-6d79538ab2a8
Content-Type: application/json

{
    "name": "A",
    "year": 2016,
    "artistId": "linck"
}
###
DELETE http://localhost:4000/album/762786df-3f17-46b7-972e-6614ec86a88e


//ARTIST
###
POST http://localhost:4000/artist
Content-Type: application/json

{
    "name": "1",
    "grammy": false
}
###
GET http://localhost:4000/artist
###
GET http://localhost:4000/artist/b0580351-2885-4d9a-bb82-ba5291bb9ad8

### 
PUT http://localhost:4000/artist/b0580351-2885-4d9a-bb82-ba5291bb9ad8
Content-Type: application/json

{
    "oldPassword": "123",
    "newPassword": "236"
}
###
DELETE http://localhost:4000/artist/65028ba0-7f61-4d67-b56d-8b06d9f4ba2d

//FAVORITES
###
POST http://localhost:4000/favs/track/a0d39357-1bd0-4a51-8f06-1c44c4e49801

###
GET http://localhost:4000/artist
###
DELETE http://localhost:4000/artist/65028ba0-7f61-4d67-b56d-8b06d9f4ba2d